python train_dreambooth.py \
    --pretrained_model_name_or_path= ## Your Model Path  \
    --instance_data_dir=  ## Your Training Input Pics Path \
    --output_dir="path-to-save-model" \
    --instance_prompt="a photo of a dog" \
    --resolution=512 \
    --train_batch_size=1 \
    --gradient_accumulation_steps=1 \
    --learning_rate=5e-6 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --num_class_images=200 \
