blank_issues_enabled: true
contact_links:
  - name: "😊 Discussions"
    url: https://github.com/hpcaitech/ColossalAI/discussions
    about: Ask questions and discuss with other Colossal-AI community members in our forum
