name: auto-parallel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - coin-or-cbc
  - pip:
    - titans
    - torch
    - pulp
    - datasets
    - colossalai
