name: Check Documentation on PR

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  check-i18n:
    name: Check docs in diff languages
    if: |
        github.event.pull_request.draft == false &&
        github.base_ref == 'main' &&
        github.event.pull_request.base.repo.full_name == 'hpcaitech/ColossalAI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.14'

      - run: python .github/workflows/scripts/check_doc_i18n.py -d docs/source
