name: Build Documentation After Merge

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'version.txt'
      - 'docs/**'
    types:
      - closed

jobs:
  build-doc:
    name: Trigger Documentation Build Workflow
    if: ( github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true ) && github.repository == 'hpcaitech/ColossalAI'
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow in ColossalAI-Documentation
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hpcaitech/ColossalAI-Documentation/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
        env:
          GH_TOKEN: ${{secrets.DOC_REPO_TOKEN}}
