name: Manual Test Example
on:
  workflow_dispatch:
    inputs:
      example_directory:
        type: string
        description: example directory, separated by comma. For example, language/gpt, images/vit. Simply input language or simply gpt does not work.
        required: true

jobs:
  manual_check_matrix_preparation:
    name: Check the examples user want
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-1.outputs.matrix }}
    steps:
    - id: set-matrix-1
      env:
        check_dir: ${{ inputs.example_directory }}
      run: | 
        IFS=','
        all_mannual_check_dir=()
        for cdi in $check_dir
        do
          all_mannual_check_dir+=("\"${cdi}\"")  
        done
        var=$( IFS=',' ; echo "${all_mannual_check_dir[*]}" )
        var="[${var}]"
        echo "$var"
        echo "::set-output name=matrix::{\"var\":$(echo "$var")}"

  manual_check:
    name: Manually check example files
    needs: manual_check_matrix_preparation
    runs-on: self-hosted
    strategy:
      matrix: ${{fromJson(needs.manual_check_matrix_preparation.outputs.matrix)}}
    container:
      image: hpcaitech/pytorch-cuda:1.12.0-11.3.0
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v3
      - name: Install the requirements
        run: |
          pip install -r ./requirements/requirements.txt
          pip install colossalai
      - name: Traverse all files
        run: |
          dir=${{ matrix.var }}
          echo "${dir} is current directory"
          cd "${PWD}/examples/${dir}"
          bash test_ci.sh
          cd ../..