name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Find the changed files
      id: find-changed-files
      uses: tj-actions/changed-files@v35
      with:
        since_last_remote_commit: true

    - uses: actions/setup-python@v3

    - name: Cache pre-commit hooks
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-hooks

    - name: Set up pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit on Changed Files
      id: precommit
      run: |
        for file in ${{ steps.find-changed-files.outputs.all_changed_files }}; do
          echo "======= running pre-commit on ${file} ======="
          pre-commit run --files $file
        done


        

    - name: Create comment
      if: always() && steps.precommit.outcome != 'success'
      uses: peter-evans/create-or-update-comment@v2
      with:
        body: |
          Pre-commit check failed because the PR author did not apply pre-commit hooks during `git commit`.

          How to resolve:
          1. install pre-commit via `pip install pre-commit`
          2. install pre-commit hooks via `pre-commit install` in the root directory of this repository
          3. run pre-commit on a single file which is changed in the commit via `pre-commit run --files <file-path>`

          Reference: https://pre-commit.com/
        reactions: heart
